version: '3.8'
services:
  db:
    image: postgres:14.2
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: payment-order
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local