version: '3.8'
services:
  db_egov_hmw1:
    image: postgres:14.2
    container_name: db_e_gov_hw1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: payment-order
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - db_egov_hmw1:/var/lib/postgresql/e-gov/hw1/data
volumes:
  db_egov_hmw1:
    driver: local